### PR TITLE
Longer color history for undoing several steps

### PR DESCRIPTION
**Pull request by styd**
- Put colors in an array of color history so that people can undo several steps behind. Because some people have much faster hands than their brains ;).

### CODE REVIEW

**Comment by styd** [comment]
Hi, Kabir. I hope you are doing well. I was wondering, did you not like the little addition I made to the back/undo function? Or is the addition against your objective for this repo? Let me know if I can improve my addition in some way to meet the purpose of this project.

Btw, my colleague really likes the site and use it a lot to try out different colors for his design. He said that it would be nice if the back button can undo several steps behind as he usually realize that the previous color is good after he moves to several new colors. That is why I made this changes.

I really hope to be able to contribute to this repo as I really like the simple design and intuitive UI.

**Comment by kbrsh** [comment]
Hey @styd!

I love the feature and have been meaning to implement it for some time now, thanks for the PR!

I will be merging via command line and making a couple changes, I personally don't like numbers next to the undo button, it doesn't look sleek, I'll also be changing the code structure, as it's pretty bad right now. Sorry for the late response, I'm a student and I was at school. 😄 

Thanks!

**Comment by styd** [comment]
Wow, you're still in school. Cool! :) I can see that you'll have a bright future.
Anyway, if you want to completely remove the #undos, you might want to remove this part in the script.js:
  $('#undos').html(colors.length - 1);
  $('#undos').css('color', colors[colors.length - 1]);
One more thing. My full name is Adrian Setyadi. Can you change my name in the list of contributors to "Adrian" instead of "Styd"? Thanks.

**Comment by kbrsh** [comment]
:smile:

I'll be sure to remove that, and I'll change your name, sorry for that 😓 

Thanks again!

**Pull request merged**
