### PR TITLE
Bug Fixes; Way Better Code Strucutre; More Stabel / Less Buggy; New Key Support, etc

### PR DESCRIPTION
**Pull request by marcmll**
Hey there Kabir, I really like this project (I found it on your Github after seeing Wing on Producthunt) and I thought I’d help fix some bugs, as well as improve the code structure, add comments and just make Colicious an even site than it already is.

Below is a summary of what I changed / added / improved, to see all the details check each of my four commits in this Pull Request.
#### Summary of Fixes, Additions and more
- Better Code Structure in all files, as well as comments for better readability and understandability
- Fixed Github Corner (now links to Github in a new tab, wherever you press on it, also preventing the trigger of a new color being
  generated)
- Clicking on the hex now copies it without changing the background color / hex in the process;
- Removed a bug where you would accidentally select the hex code or the button itself when clicking to find a new color
- Added support for the backspace and left arrow key to return the same functionality as the back arrow
- Added support for the right arrow key to generate a new color (same as space)

Hope you accept my pull request and we can continue developing Colicious to become better and better over time.

### CODE REVIEW

**Comment by kbrsh** [comment]
Hey Marc,

Thank you so much, I am glad that you liked Colicious! 

I would rate the code quality of Colicious 3/10, and didn't even want to touch it or try to improve it. 

I _really_ appreciate that you took the time to do all of this, it really helps :+1: 

Thanks,
Kabir Shah

**Comment by kbrsh** [comment]
The footer is really messing with the UI, should we remove it completely?

**Comment by marcmll** [comment]
How is it messing it up? @KingPixil

**Comment by kbrsh** [comment]
It just clutters the whole UI.

**Comment by kbrsh** [comment]
I guess we can keep it :)

**Comment by marcmll** [comment]
Can you show me a screenshot or something? For me it seems fine.

**Comment by kbrsh** [comment]
It works fine, its just that the footer is big and bright, maybe we should make it smaller so the user can focus more on Colicious, I have been meaning to do this but I didn't get a chance.

**Comment by marcmll** [comment]
If you want you can make it smaller, I don't have anything against it. I have a few ideas for Colicious, like features, we could try adding, etc. Maybe we can talk about that when we both have time (currently, I need to go sleep, it's 1:39 am)... Would be awesome to know your timezone, maybe we can find a time to talk via appear.in or so. If you ever want to contact me: my mail is momueller@me.com

**Comment by kbrsh** [comment]
Cool, I live in California, and I will contact you when necessary. Thanks :+1:

**Comment by marcmll** [comment]
Ah, nice I live in Berlin... So 9 hours difference it is. We can probably find a time tho and then we can talk about how we could continue developing Colicious.

**Comment by kbrsh** [comment]
Cool :)

**Comment by kbrsh** [comment]
One thing, I noticed that you added your name to the footer.

I have nothing against you, but I think it is a bit unfair to do this. Is it cool if I remove it? I can add you in the README or something, but its just that I spent a very long time working on this and launching it, getting first on Product Hunt, etc. 

:smile: I totally appreciate the work you've done though, and hope that this doesn't hurt you in any way.

**Comment by marcmll** [comment]
Yes, if you wish you can take it out, but it would be amazing if I could at least be in the README, to display that I have helped work on this project.

**Comment by kbrsh** [comment]
Awesome! Hope you understand, and I will add you in the README, as you have done a lot of work :)

**Pull request merged**
